//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitiLightningDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strategy
    {
        public int Id { get; set; }
        public string Ticker { get; set; }
        public string Name { get; set; }
        public Nullable<int> LongPosition { get; set; }
        public Nullable<int> ShortPosition { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> NumberOfShares { get; set; }
        public Nullable<decimal> PercentChange { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> StrategyActive { get; set; }
    }
}
